### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by Jo-won** [YuweiYin/FinPT#2]
Hello, thank you for releasing your code. However, I have a question.

When I tried to reproduce the result of FinBERT on CF1, the test F1 score was not the same as in your paper.

Paper: 45.1
Reproduced: 34.3
I suspect the problem may stem from unspecified package versions. Although I have spent a lot of time trying to align the package versions with the code, I almost didn't modify the code.

Could you inform me about the specific versions of the packages? If you have any ideas about other possible issues, sharing them would also help me solve this problem.

**Comment by YuweiYin** [comment]
Hi Won,

Thanks for your attention.

The package version might not influence much. As for the FinBERT model, we used [finbert-pretrain](https://huggingface.co/yiyanghkust/finbert-pretrain). Actually, the accuracy scores fluctuate, and the results in the paper are averaged over multiple trials under different random seeds.

In general, the proposed FinPT method provides a framework to leverage the power of language models for financial tabular data and outperforms most baselines by tuning Flan-T5. The provided pipeline (Steps 1, 2, and 3) helps re-implementation of incorporating more models and financial/tabular datasets.
